spring:
  application:
    name: wfh
  datasource:
    url: jdbc:postgresql://dpg-cva7d0rqf0us73cfvjb0-a.oregon-postgres.render.com:5432/wfh_database
    driverClassName: org.postgresql.Driver
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-38ur00tkntqcylhl.us.auth0.com/
          audience: https://dev-38ur00tkntqcylhl.us.auth0.com/api/v2/


security:
  jwt:
    secret-key: b8396c432a0d45c1efc70a38d76ef49a3272570305b5c382a569ebaa50c95ed9
    expiration-time: 36000

user:
  info:
    url: https://dev-38ur00tkntqcylhl.us.auth0.com/userinfo

logging:
  level:
    com.radz.wfh: INFO

allowed:
  origin: ${ALLOWED_HOST}

management:
  endpoints:
    web:
      exposure:
        include: health

